# Generated by Django 5.1.2 on 2024-10-09 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provedor', models.CharField(max_length=75, verbose_name='id_provedor')),
                ('telefono', models.IntegerField(max_length=8, verbose_name='telefono')),
                ('gmail', models.CharField(max_length=75, verbose_name='gmail')),
                ('raiting', models.CharField(max_length=1, verbose_name='raiting')),
                ('registro_fehca', models.DateField(max_length=75, verbose_name='registro fecha')),
                ('tipo', models.CharField(max_length=10, verbose_name='tipo')),
                ('provincia', models.CharField(max_length=75, verbose_name='provincia')),
            ],
            options={
                'verbose_name': 'Provedores',
                'verbose_name_plural': 'Provedor',
                'db_table': 'Provedor',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.CharField(max_length=75, verbose_name='id_sucursal')),
                ('direccion', models.CharField(max_length=75, verbose_name='direccion')),
                ('ciudad', models.CharField(max_length=75, verbose_name='ciudad00')),
                ('nombre', models.CharField(max_length=75, verbose_name='nombre')),
                ('encargado', models.CharField(max_length=75, verbose_name='encargado')),
                ('telefono', models.IntegerField(max_length=8, verbose_name='telefono')),
                ('horario', models.IntegerField(max_length=4, verbose_name='horario')),
                ('provedores_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.provedores')),
            ],
        ),
    ]
